AllCops:
  Exclude:
    - db/**/*
    - features/**/*
    - '**/migrations/**'
    - bin/**/*
LineLength:
  Max: 160
  Enabled: true
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics:
  Enabled: false
