AllCops:
  Exclude:
    - db/**/*
    - features/**/*
    - '**/migrations/**'
    - spec/**/*
    - bin/**/*
LineLength:
  Max: 100
  Enabled: true
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
