AllCops:
  Exclude:
    - db/**/*
    - features/**/*
    - db/**/*
    - spec/factories/**/*
LineLength:
  Max: 100
  Enabled: true
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
